# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raul Hernandez | Desarrollo Web.
email: awce5nk@hotmail.com
description: > Desarrollador, BackEnd y FrontEnd en Tecnologías Web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://awce.me" # the base hostname & protocol for your site
twitter_username: awce2
github_username:  awce

# Build settings
markdown: kramdown

gems: ['kramdown']
#permalink: pretty
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
